[core]
restore_state = true

[mpd]
enabled = true
hostname = ::

[audio]
output = pulsesink server=127.0.0.1 
buffer_time = 1000

[spotify]
enabled = true
client_id = bc07d5aa-a218-4590-9bbe-f0488c604a3f
client_secret = _UN0Jv2_-O-npYEp2YllCHjYn5ANCZpZJ-hEzJbcF54=

[iris]
enabled = true

[file]
enabled = true
media_dirs = 
  /media/data/Music/Game
show_dotfiles = false
excluded_file_extensions =
  .directory
  .html
  .jpeg
  .jpg
  .log
  .nfo
  .pdf
  .png
  .txt
  .zip
follow_symlinks = false
metadata_timeout = 1000
